#!/usr/bin/env node
// design-surface.mjs — deterministic Tier-1 Design Surface generator + audit
// library for agentic-governance. Plain Node, zero dependencies (node: imports
// only), same style as governance-checks.mjs. Runs against the adopting repo
// (git toplevel of the cwd), NOT the directory holding this script.
//
// The generator NEVER fabricates: a missing declared source produces a visible
// gap and a non-zero exit (the projection rule, spec §3). See docs/design-surface.md.
//
// Usage:
//   node design-surface.mjs                          # generate Tier-1 + manifest
//   node design-surface.mjs --delta docs/governance-delta.md  # delta path override
//   node design-surface.mjs --out docs/design        # output dir override

import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const SCRIPT_DIR = path.dirname(url.fileURLToPath(import.meta.url));

// ---------- hashing ----------

export function sha256(buf) {
  return createHash('sha256').update(buf).digest('hex');
}
export function hashString(s) {
  return sha256(Buffer.from(s, 'utf8'));
}
export function hashFile(absPath) {
  return sha256(fs.readFileSync(absPath));
}

// ---------- environment ----------

export function gitToplevel(cwd = process.cwd()) {
  return execFileSync('git', ['rev-parse', '--show-toplevel'], { cwd, encoding: 'utf8' }).trim();
}
// The canonical package version this generator ships in (agentic-governance/VERSION),
// two levels up from governance/scripts/.
export function governanceVersion() {
  return fs.readFileSync(path.join(SCRIPT_DIR, '..', '..', 'VERSION'), 'utf8').trim();
}

// ---------- markdown + delta parsing ----------

// Body of a `## <name>` section, trimmed, up to the next `## ` heading or EOF.
export function section(text, name) {
  const lines = text.split('\n');
  let inSec = false;
  const out = [];
  for (const line of lines) {
    if (new RegExp(`^##\\s+${name}\\s*$`).test(line)) {
      inSec = true;
      continue;
    }
    if (inSec && /^##\s+/.test(line)) break;
    if (inSec) out.push(line);
  }
  return out.join('\n').trim();
}

function norm(v) {
  if (v === null || v === undefined) return null;
  return /^none$/i.test(v.trim()) ? null : v.trim();
}

export function parseDeltaBlock(deltaText) {
  if (!/^##\s+Design Surface\s*$/m.test(deltaText)) return null;
  const body = section(deltaText, 'Design Surface');
  const bodyLines = body.split('\n');
  const field = (label) => {
    for (const raw of bodyLines) {
      const l = raw.replace(/\s+#.*$/, '').trim(); // strip trailing " # comment"
      const m = l.match(new RegExp(`^${label}\\s*:\\s*(.*)$`, 'i'));
      if (m) return m[1].trim();
    }
    return null;
  };
  return {
    status: (field('Status') || 'DISABLED').toUpperCase(),
    taxonomySource: norm(field('Taxonomy source')),
    taxonomyRendered: norm(field('Taxonomy rendered')),
    adrDir: field('ADR dir') || 'docs/adr',
    memoryBank: norm(field('Memory bank')),
    narrativeSources: (field('Narrative sources') || '')
      .split(',')
      .map((s) => s.trim())
      .filter(Boolean),
    outputDir: field('Output dir') || 'docs/design',
    pagesMechanism: (field('Pages mechanism') || 'none').toLowerCase(),
    narrativeReview: field('Narrative review') || 'required',
  };
}

// ---------- Tier-1 source hashing ----------

export function adrFiles(root, adrRel) {
  const dir = path.join(root, adrRel);
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((f) => /^\d{4}-.*\.md$/.test(f) && f !== '0000-template.md')
    .sort();
}
function adrStatus(root, adrRel, file) {
  const m = fs.readFileSync(path.join(root, adrRel, file), 'utf8').match(/^Status:\s*(\w+)/m);
  return m ? m[1] : null;
}
export function adrSetHash(root, adrRel, gaps) {
  const dir = path.join(root, adrRel);
  if (!fs.existsSync(dir)) {
    gaps.push(`missing ADR dir: ${adrRel}`);
    return null;
  }
  const parts = adrFiles(root, adrRel).map((f) => `${f.slice(0, 4)}:${adrStatus(root, adrRel, f) || '?'}`);
  return hashString(parts.join('|'));
}

export function adrMeta(root, adrRel, file) {
  const text = fs.readFileSync(path.join(root, adrRel, file), 'utf8');
  const id = (file.match(/^(\d{4})/) || [])[1] || '';
  const titleM = text.match(/^#\s*(?:ADR-\d+:\s*)?(.+?)\s*$/m);
  const statusM = text.match(/^Status:\s*(\w+)/m);
  const sup = section(text, 'Supersedes');
  const supersedes = !sup || /^none\.?$/i.test(sup) ? null : sup.replace(/^[-*]\s*/, '').split('\n')[0].trim();
  return {
    id,
    title: titleM ? titleM[1] : file,
    status: statusM ? statusM[1] : null,
    supersedes,
  };
}

export function buildAdrIndex(root, adrRel, gaps) {
  const files = adrFiles(root, adrRel);
  const head = '# ADR Index\n\n_Generated by design-surface.mjs (Tier 1) — do not edit by hand._\n';
  if (!fs.existsSync(path.join(root, adrRel))) {
    return `${head}\n> **GAP:** declared ADR dir \`${adrRel}\` is missing.\n`;
  }
  if (files.length === 0) {
    return `${head}\n_No ADRs found in \`${adrRel}\`._\n`;
  }
  const rows = files.map((f) => {
    const m = adrMeta(root, adrRel, f);
    return `| ${m.id} | ${m.title} | ${m.status || '?'} | ${m.supersedes || '—'} |`;
  });
  return `${head}\n| ADR | Title | Status | Supersedes |\n| --- | --- | --- | --- |\n${rows.join('\n')}\n`;
}

export function memoryBankFiles(root, memRel) {
  const dir = path.join(root, memRel);
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith('.md'))
    .sort();
}
export function memoryBankRev(root, memRel, gaps) {
  if (!memRel) return null;
  const dir = path.join(root, memRel);
  if (!fs.existsSync(dir)) {
    gaps.push(`missing memory bank: ${memRel}`);
    return null;
  }
  const h = createHash('sha256');
  for (const f of memoryBankFiles(root, memRel)) {
    h.update(f);
    h.update('\0');
    h.update(fs.readFileSync(path.join(dir, f)));
  }
  return h.digest('hex');
}

export function taxonomyHash(root, decl, gaps) {
  if (!decl.taxonomySource) return null;
  const p = path.join(root, decl.taxonomySource);
  if (!fs.existsSync(p)) {
    gaps.push(`missing taxonomy source: ${decl.taxonomySource}`);
    return null;
  }
  return hashFile(p);
}

// ---------- taxonomy inclusion (Tier 1; zero-dep refinement, spec §4.1) ----------

// The generator does NOT parse the taxonomy source (no stdlib YAML parser).
// The repo already renders its taxonomy; the delta declares both the
// pre-rendered artifact (included verbatim here) and the raw source (hashed
// in taxonomyHash/computeManifest). Returns null when taxonomy is domain-
// specific and not declared ("none").
export function buildTaxonomy(root, decl, gaps) {
  if (!decl.taxonomyRendered) return null; // domain-specific; omit the section
  const abs = path.join(root, decl.taxonomyRendered);
  if (!fs.existsSync(abs)) {
    gaps.push(`taxonomy: declared rendered artifact not found: ${decl.taxonomyRendered}`);
    return {
      filename: 'taxonomy.md',
      markdown: `# Taxonomy\n\n_missing declared taxonomy artifact: \`${decl.taxonomyRendered}\`_\n`,
    };
  }
  const body = fs.readFileSync(abs, 'utf8').trimEnd();
  const header = `<!-- Generated by design-surface.mjs from ${decl.taxonomyRendered} (source: ${decl.taxonomySource ?? 'n/a'}). Do not edit. -->\n\n`;
  return { filename: 'taxonomy.md', markdown: `${header}${body}\n` };
}

// ---------- module map + status (Tier 1) ----------

function walkTree(absDir, relDir, ignore, depth, maxDepth, lines) {
  if (depth > maxDepth) return;
  const entries = fs
    .readdirSync(absDir, { withFileTypes: true })
    .filter((e) => !e.name.startsWith('.'))
    .filter((e) => {
      const rel = relDir ? `${relDir}/${e.name}` : e.name;
      return !ignore.includes(e.name) && !ignore.includes(rel);
    })
    .sort((a, b) => a.name.localeCompare(b.name));
  for (const e of entries) {
    const rel = relDir ? `${relDir}/${e.name}` : e.name;
    lines.push(`${'  '.repeat(depth)}- ${e.name}${e.isDirectory() ? '/' : ''}`);
    if (e.isDirectory()) {
      walkTree(path.join(absDir, e.name), rel, ignore, depth + 1, maxDepth, lines);
    }
  }
}

// Deterministic, sorted, ignore-filtered, depth-limited directory tree of the
// repo. Same inputs always produce the same output (no timestamps, no
// filesystem-order dependence — entries are sorted at every level).
export function buildModuleMap(root, { ignore, outRel }) {
  const skip = [...new Set([...(ignore || []), '.git', 'node_modules', outRel])];
  const lines = [];
  walkTree(root, '', skip, 0, 3, lines);
  return `# Architecture\n\nDeterministic module/package tree (depth ≤ 3), generated from the repository layout.\n\n${lines.join('\n')}\n`;
}

export function buildStatus(root, decl, manifest) {
  const memFiles = decl.memoryBank
    ? memoryBankFiles(root, decl.memoryBank).map((f) => `- \`${decl.memoryBank}/${f}\``)
    : [];
  return [
    '# Status',
    '',
    `- Governance version: \`${manifest.governance_version}\``,
    `- Design Surface: \`${decl.status}\``,
    `- Pages mechanism: \`${decl.pagesMechanism}\``,
    `- Generated at: \`${manifest.generated_at}\``,
    '',
    '## Memory bank',
    '',
    ...(memFiles.length ? memFiles : ['- _none declared_']),
    '',
  ].join('\n');
}

// ---------- manifest ----------

export function computeManifest(root, decl, opts = {}) {
  const gaps = opts.gaps || [];
  const now = opts.now || new Date().toISOString();
  const taxonomy_hash = taxonomyHash(root, decl, gaps);
  const adr_set_hash = adrSetHash(root, decl.adrDir, gaps);
  const memory_bank_rev = memoryBankRev(root, decl.memoryBank, gaps);
  const narrative_inputs_hash = hashString([taxonomy_hash, adr_set_hash, memory_bank_rev].join('|'));
  return {
    taxonomy_hash,
    adr_set_hash,
    memory_bank_rev,
    narrative_inputs_hash,
    generated_at: now,
    governance_version: governanceVersion(),
  };
}

// ---------- generate (Tier-1 orchestration; extended in later tasks) ----------

export function generate(root, decl, outRel, opts = {}) {
  const gaps = [];
  const manifest = computeManifest(root, decl, { now: opts.now, gaps });
  const outDir = path.join(root, outRel);
  fs.mkdirSync(outDir, { recursive: true });
  const write = (name, content) =>
    fs.writeFileSync(path.join(outDir, name), content.endsWith('\n') ? content : content + '\n');
  write('design-surface-manifest.json', JSON.stringify(manifest, null, 2));
  write('adr-index.md', buildAdrIndex(root, decl.adrDir, gaps));
  const tax = buildTaxonomy(root, decl, gaps);
  if (tax) write(tax.filename, tax.markdown);
  write('architecture.md', buildModuleMap(root, { ignore: [outRel], outRel }));
  write('status.md', buildStatus(root, decl, manifest));
  return { manifest, gaps };
}

// ---------- drift audit (--design-surface, advisory; spec §5) ----------

export function readPublishedManifest(root, outRel) {
  const p = path.join(root, outRel, 'design-surface-manifest.json');
  if (!fs.existsSync(p)) return null;
  try {
    return JSON.parse(fs.readFileSync(p, 'utf8'));
  } catch {
    return null;
  }
}

export function narrativeStampedHash(root, narrativeRel) {
  const p = path.join(root, narrativeRel);
  if (!fs.existsSync(p)) return null;
  const m = fs.readFileSync(p, 'utf8').match(/narrative_inputs_hash:\s*([0-9a-f]+)/i);
  return m ? m[1] : null;
}

// Compares the current sources against the published manifest and the
// narrative's stamped hash. Advisory only: never throws, never blocks — the
// caller (governance-checks.mjs --design-surface) prints WARN and exits 0.
export function auditDesignSurface(root, decl, { out, narrative }) {
  const findings = [];
  const gaps = [];
  const current = computeManifest(root, decl, { now: '', gaps });
  for (const g of gaps) findings.push({ kind: 'missing-source', message: g });

  const published = readPublishedManifest(root, out);
  if (published) {
    for (const k of ['taxonomy_hash', 'adr_set_hash', 'memory_bank_rev']) {
      if (published[k] !== current[k]) {
        findings.push({ kind: 'tier-1-out-of-date', message: `${k} differs from published surface (regenerate Tier 1 in CI)` });
      }
    }
  }
  if (narrative) {
    const stamped = narrativeStampedHash(root, narrative);
    if (stamped !== current.narrative_inputs_hash) {
      findings.push({ kind: 'stale-narrative', message: 'narrative is stale vs current sources — run /governance:publish-design-surface' });
    }
  }
  return findings;
}

// ---------- CLI ----------

export function parseArgs(argv) {
  const args = argv.slice(2);
  const val = (flag, fb) => {
    const i = args.indexOf(flag);
    return i >= 0 ? args[i + 1] : fb;
  };
  return {
    delta: val('--delta', 'docs/governance-delta.md'),
    out: val('--out', null),
    designSurface: args.includes('--design-surface'),
  };
}

export function main(argv = process.argv) {
  const opts = parseArgs(argv);
  const root = gitToplevel();
  const decl = parseDeltaBlock(fs.readFileSync(path.join(root, opts.delta), 'utf8'));
  if (!decl || decl.status !== 'ENABLED') {
    console.log('design-surface: capability DISABLED or not declared; nothing to do.');
    return 0;
  }
  const outRel = opts.out || decl.outputDir;
  const { gaps } = generate(root, decl, outRel);
  if (gaps.length) {
    console.error('design-surface: gaps found (missing declared sources — never fabricated):');
    for (const g of gaps) console.error(`  - ${g}`);
    return 1;
  }
  console.log(`design-surface: Tier-1 surface written to ${outRel}`);
  return 0;
}

if (process.argv[1] && url.fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  process.exit(main());
}
